BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
SPLIT_KEYBOARD   = yes      # Enable Split Keyboard
NKRO_ENABLE      = yes      # Enable N-Key Rollover
RGBLIGHT_ENABLE  = yes      # Enable keyboard RGB underglow
MOUSEKEY_ENABLE  = no       # Mouse keys
EXTRAKEY_ENABLE  = no       # Audio control and System control
CONSOLE_ENABLE   = no       # Console for debug
COMMAND_ENABLE   = no       # Commands for debug and configuration
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
AUDIO_ENABLE     = no       # Audio output
ENCODER_ENABLE   = no       # Enable Rotary Encoders
OLED_ENABLE      = no       # Enable OLED Displays
